/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : bigint, 'foodItem' : FoodItem }
export type Category = { 'healthyFoods' : null } |
  { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'fastFood' : null } |
  { 'snacks' : null } |
  { 'nonVegetarian' : null } |
  { 'dinner' : null } |
  { 'vegetarian' : null };
export interface FoodItem {
  'id' : bigint,
  'categories' : Array<Category>,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'prepTime' : bigint,
  'price' : number,
}
export interface OrderRecord {
  'id' : bigint,
  'status' : OrderStatus,
  'user' : Principal,
  'items' : Array<CartItem>,
  'totalPrice' : number,
}
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFoodItem' : ActorMethod<[FoodItem], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateCartTotal' : ActorMethod<[], number>,
  'deleteFoodItem' : ActorMethod<[bigint], undefined>,
  'getAllFoodItems' : ActorMethod<[], Array<FoodItem>>,
  'getAllOrdersByTotalPriceDesc' : ActorMethod<[], Array<OrderRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getFoodItemsByCategory' : ActorMethod<[Category], Array<FoodItem>>,
  'getOrderHistory' : ActorMethod<[], Array<OrderRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], bigint>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateFoodItem' : ActorMethod<[FoodItem], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];