/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'healthyFoods' : IDL.Null,
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'fastFood' : IDL.Null,
  'snacks' : IDL.Null,
  'nonVegetarian' : IDL.Null,
  'dinner' : IDL.Null,
  'vegetarian' : IDL.Null,
});
export const FoodItem = IDL.Record({
  'id' : IDL.Nat,
  'categories' : IDL.Vec(Category),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'preparationTime' : IDL.Nat,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'foodItem' : FoodItem,
});
export const OrderRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'user' : IDL.Principal,
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFoodItem' : IDL.Func([FoodItem], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateCartTotal' : IDL.Func([], [IDL.Float64], ['query']),
  'deleteFoodItem' : IDL.Func([IDL.Nat], [], []),
  'getAllOrdersByTotalPriceDesc' : IDL.Func(
      [],
      [IDL.Vec(OrderRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
  'getFoodItemsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(FoodItem)],
      ['query'],
    ),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [IDL.Nat], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateFoodItem' : IDL.Func([FoodItem], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'healthyFoods' : IDL.Null,
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'fastFood' : IDL.Null,
    'snacks' : IDL.Null,
    'nonVegetarian' : IDL.Null,
    'dinner' : IDL.Null,
    'vegetarian' : IDL.Null,
  });
  const FoodItem = IDL.Record({
    'id' : IDL.Nat,
    'categories' : IDL.Vec(Category),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'preparationTime' : IDL.Nat,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'foodItem' : FoodItem });
  const OrderRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'user' : IDL.Principal,
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFoodItem' : IDL.Func([FoodItem], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateCartTotal' : IDL.Func([], [IDL.Float64], ['query']),
    'deleteFoodItem' : IDL.Func([IDL.Nat], [], []),
    'getAllOrdersByTotalPriceDesc' : IDL.Func(
        [],
        [IDL.Vec(OrderRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
    'getFoodItemsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(FoodItem)],
        ['query'],
      ),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [IDL.Nat], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateFoodItem' : IDL.Func([FoodItem], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };